### ISSUE TITLE
error in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by jpbsilva** [microsoft/pgtoolsservice#218]
Module not working in openSUSE Tumbleweed.

Just after install the plugin oet the error below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/attach_server.py", line 35, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ptvsd/visualstudio_py_debugger.py", line 24, in <module>
  File "/usr/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 15:36:08] Connection to server got closed. Server will not be restarted.

**Comment by stevedorries** [comment]
I'm getting the same error in openSUSE Leap 15.0 as of 11 November, 2019
```
$ rpm -qa | grep libffi
libffi7-32bit-3.2.1.git259-lp150.3.3.x86_64
libffi-devel-3.2.1.git259-lp150.3.3.x86_64
libffi7-3.2.1.git259-lp150.3.3.x86_64
```

### Janky, Not at All Recommended Workaround
I created a symlink to `/usr/lib64/libffi.so` called `/usr/lib64/libffi.so.6` then uninstalled the extension and installed it fresh, the error wasn't reproduced. Now, I'm not entirely certain if there are any breaking changes that would make this crash at runtime, and I AM 100% certain that this is not the right way to fix it, but it seems to have worked for me, for now.

**Comment by jpbsilva** [comment]
Yes, this is a workaround, not a good solution.

I did the same:
```
[root@nb2 ~]# l /usr/lib64/libffi*
lrwxrwxrwx 1 root root  15 Oct 17 07:24 /usr/lib64/libffi.so -> libffi.so.7.1.0
lrwxrwxrwx 1 root root  11 Oct 16 13:13 /usr/lib64/libffi.so.6 -> libffi.so.7
lrwxrwxrwx 1 root root  15 Oct 17 07:24 /usr/lib64/libffi.so.7 -> libffi.so.7.1.0
-rwxr-xr-x 1 root root 43K Oct 17 07:24 /usr/lib64/libffi.so.7.1.0
[root@nb2 ~]# 

```

**Comment by sgryphon** [comment]
There are multiple copies of this same bug, but this issue (#218) is the earliest I can find open.

This bug should be fixed. There is a comment about fixing it on one of the duplicates (https://github.com/microsoft/pgtoolsservice/issues/251)

They have the same error, a dialog that pops up on start and says "ImportError: libffi.so.6: cannot open shared object file: No such file or directory", then an error reported in the output section:

```
"It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
... a stack trace ...
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:57:17 PM] Connection to server got closed. Server will not be restarted."
```

The important bit is the missing "libffi.so.6"

There are many other duplicates (that should probably be closed and directed to here)

https://github.com/microsoft/pgtoolsservice/issues/239
https://github.com/microsoft/pgtoolsservice/issues/251
https://github.com/microsoft/pgtoolsservice/issues/275
https://github.com/microsoft/pgtoolsservice/issues/279
https://github.com/microsoft/pgtoolsservice/issues/280
https://github.com/microsoft/pgtoolsservice/issues/282
https://github.com/microsoft/pgtoolsservice/issues/283

**Work around:**

So far, the workaround for some systems linking libffi.so.6 to version 7 seems to work:
 
```
sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails. You can check which version you have via:

```
ls -la /usr/lib/x86_64-linux-gnu/libffi*
```

The other workaround is to directly install the version 6 libraries directly:

```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by cbcoutinho** [comment]
For those who are coming here for openSUSE Tumbleweed (or others that only offer version 8 of `libffi`) see the note above:

> The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails.

I found that the server:monitoring` repo on OBS still offers `libffi6`, which you can access by adding the following repo:

```bash
$ sudo zypper ar https://download.opensuse.org/repositories/server:monitoring/openSUSE_Tumbleweed/server:monitoring.repo
$ sudo zypper ref
$ sudo zypper install libffi6
```

**Comment by reporter123** [comment]
This most defiantly is not fixed yet or the VSCode postgres Extension is pulling an outdate version.

**Comment by santhosh-reddy03** [comment]
the ptvsd(python tool for vs debugger) module which is being used in ossdbtoolsservice_main.py is no longer active, looks the same old module is being shipped and its creating issues, the ubuntu 20.04 uses newer version which is libffi.so.7.1.0.

**Comment by dingobar** [comment]
It's been years, and this has not been fixed. Trying to run ADS on Ubuntu 22.04 (Jammy Jellyfish) to no avail. Anyone successfuly installed and used the extension on 22.04?

**Comment by reporter123** [comment]
ptvsd appears to be dead that is root cause of this issue.
