### ISSUE TITLE
OSS DB Tools Service component exited unexpectedly. Please restart Azure Data Studio. Source: PostgreSQL (Extension)

### ISSUE THREAD

**Issue by edeortuzar** [microsoft/pgtoolsservice#280]
On Ubuntu 20.10 after install the PostgreSQL plugin I have this error and I can't use Azure Data Studio to connect a database.

**Comment by FiresideCode** [comment]
Had the same issue today.

**Comment by alexmetelli** [comment]
Same issue on Arch and Azure Studio Postgres extension crashing right after launch

**Comment by TiagoValdrich** [comment]
Same issue on Pop OS 20.04, using the PostgreSQL extension.

**Comment by carloshorstmann** [comment]
I Resolve this creating a symbolic link:

sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

**Comment by moccy** [comment]
I fixed this on Arch Linux by installing the libffi6 AUR package: https://aur.archlinux.org/packages/libffi6/

**Comment by villecoder** [comment]
Running Ubuntu 21.04.

I took @carloshorstmann 's advice, but I have libffi.so.8.  So my command was:

```
sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.8 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

However, I still cannot open a pgsql connection.  My Tasks output reads as follows:

```
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
[Error - 3:11:15 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by shifu137** [comment]
> I Resolve this creating a symbolic link:
> 
> sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

Thanks! this worked for me on Linux Mint 20.1

**Comment by sgryphon** [comment]
Appears to be a duplicate of https://github.com/microsoft/pgtoolsservice/issues/218 and should be closed.

They have the same error, a dialog that pops up on start and says "ImportError: libffi.so.6: cannot open shared object file: No such file or directory", then an error reported in the output section:

```
"It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
... a stack trace ...
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:57:17 PM] Connection to server got closed. Server will not be restarted."
```

The important bit is the missing "libffi.so.6"

There are many other duplicates (that should probably be closed as well)

https://github.com/microsoft/pgtoolsservice/issues/239
https://github.com/microsoft/pgtoolsservice/issues/251
https://github.com/microsoft/pgtoolsservice/issues/275
https://github.com/microsoft/pgtoolsservice/issues/279
https://github.com/microsoft/pgtoolsservice/issues/280
https://github.com/microsoft/pgtoolsservice/issues/282
https://github.com/microsoft/pgtoolsservice/issues/283

**Work around:**

So far, the workaround for some systems linking libffi.so.6 to version 7 seems to work:
 
```
sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails. You can check which version you have via:

```
ls -la /usr/lib/x86_64-linux-gnu/libffi*
```

The other workaround is to directly install the version 6 libraries directly:

```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by jrrfilho** [comment]
> Running Ubuntu 21.04.
> 
> I took @carloshorstmann 's advice, but I have libffi.so.8. So my command was:
> 
> ```
> sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.8 /usr/lib/x86_64-linux-gnu/libffi.so.6
> ```
> 
> However, I still cannot open a pgsql connection. My Tasks output reads as follows:
> 
> ```
> It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
> This may make the debugger miss breakpoints in the standard library.
> Related bug: https://bugs.python.org/issue1180193
> [Error - 3:11:15 PM] Connection to server got closed. Server will not be restarted.
> ```

In my case de installed version was libffi.so.7. Looking for the version of your libffi installed using Synaptic before running the command above.

**Comment by relationaldba** [comment]
Got the same error on Ubuntu 22.04. My system has libffi8 installed and creating a symbolic link to `/usr/lib/x86_64-linux-gnu/libffi.so.8` does not work.

I was able to resolve it by installing libffi7 and then creating a symbolic link to /usr/lib/x86_64-linux-gnu/libffi.so.7

`
sudo apt install libffi7
sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
`

**Comment by ianw1974** [comment]
On Fedora 37, this can be resolved by installing ```libffi3.1```:

```
[root@elise ~]# dnf whatprovides libffi.so.6
Last metadata expiration check: 0:06:50 ago on Tue 28 Feb 2023 22:31:53 CET.
libffi3.1-3.1-32.fc36.i686 : Compatibility package for libffi transition from 3.1 to 3.4.2.
Repo        : fedora
Matched from:
Provide    : libffi.so.6
```

as the base libffi package is for ```libffi.so.8```.

**Comment by ianw1974** [comment]
And for Fedora 38:

`dnf install libffi3.1`

will resolve the issue

**Comment by nasc17** [comment]
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.2 using pgtoolsservice v1.8.0. We would appreciate your verification that it has been handled appropriately.
